replace_word = {
    'aja': 'saja',
    'aq':'saya',
    'ad':'ada',
    'aj':'saja',
    'abis':'habis',
    'ama':'sama',
    'bpk':'bapak',
    'bkn':'bukan',
    'bodo':'bodoh',
    'bnyk':'banyak',
    'byk':'banyak',
    'bg': 'bang',
    'bs':'bisa',
    'blm':'belum',
    'berfikir': 'berpikir',
    'bg':'bang',
    'bgt':'banget',
    'cm':'cuma',
    'd': 'di',
    'dah':'sudah',
    'dlm': 'dalam',
    'dgn': 'dengan',
    'dpt':'dapat',
    'dll':'dan lain lain',
    'dg': 'dengan',
    'dri':'dari',
    'dr': 'dari',
    'dn':'dan',
    'dunggu':'dungu',
    'esmosi':'emosi',
    'g': 'tidak',
    'gmn':'gimana',
    'gak': 'tidak',
    'gk':'tidak',
    'gaklama':'tidak lama',
    'garung':'gerung',
    'ga': 'tidak',
    'gua': 'saya',
    'gw': 'saya',
    'gue': 'saya',
    'jgn':'jangan',
    'jd': 'jadi',
    'jg':'juga',
    'jdi':'jadi',
    'kalo': 'kalau',
    'kau': 'kamu',
    'krna':'karena',
    'kek': 'seperti',
    'kyk': 'seperti',
    'klo': 'kalau',
    'knp': 'kenapa',
    'koq':'kok',
    'ko':'kok',
    'klau':'kalau',
    'kl':'kalau',
    'klu':'kalau',
    'krn':'karena',
    'komen':'komentar',
    'klw':'kalau',
    'lg':'lagi',
    'lawa':'lawak',
    'liat':'lihat',
    'lu':'anda',
    'lo':'anda',
    'mutar':'putar',
    'muter': 'putar',
    'moga':'semoga',
    'mmg':'memang',
    'ni':'ini',
    'n':'dan',
    'ny':'nya',
    'nggak': 'tidak',
    'ngga':'tidak',
    'ngk':'tidak',
    'org': 'orang',
    'orng':'orang',
    'p': 'bapak',
    'pengen':'ingin',
    'pk':'pakai',
    'penghianat':'pengkhianat',
    'rg': 'rocky gerung',
    'roki': 'rocky',
    'rokky': 'rocky',
    'roky': 'rocky',
    'rocki': 'rocky',
    'rock':'rocky',
    'sampe': 'sampai',
    'silvester': 'silfester',
    'sylvester': 'silfester',
    'silpester':'silfester',
    'silfer':'silfester',
    'spt':'seperti',
    'sd':'sekolah dasar',
    'sdh':'sudah',
    'sy': 'saya',
    'sm':'sama',
    'sma':'sama',
    'tak': 'tidak',
    'tdk': 'tidak',
    'terimakasih':'terima kasih',
    'tp': 'tapi',
    'trs':'terus',
    'trus':'terus',
    'tu':'itu',
    'tpi':'tapi',
    'utk': 'untuk',
    'udh':'sudah',
    'vs':'versus',
    'yg': 'yang',
    'ya':'iya'
}